name: Incident Report

on:
  repository_dispatch:
    types:
      - incident_report

jobs:
  handle-incident:

    runs-on: ubuntu-latest

    steps:

      - name: Print Incident Details
        run: |
          echo "Severity: ${{ github.event.client_payload.severity }}"
          echo "Service: ${{ github.event.client_payload.service }}"
          echo "Message: ${{ github.event.client_payload.message }}"

      - name: Send Incident Email
        uses: dawidd6/action-send-mail@v18
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true

          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}

          from: ${{ secrets.MAIL_USERNAME }}
          to: ahmed.ferganey707@gmail.com

          subject: "Incident: ${{ github.event.client_payload.service }}"

          body: |
            A new incident has been reported.

            Severity:
            ${{ github.event.client_payload.severity }}

            Service:
            ${{ github.event.client_payload.service }}

            Incident:
            ${{ github.event.client_payload.message }}

            Repository:
            ${{ github.repository }}

            Triggered By:
            ${{ github.actor }}